
import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.57.4";
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{"Content-Type":"application/json"}});
function hex(bytes:ArrayBuffer){return [...new Uint8Array(bytes)].map(b=>b.toString(16).padStart(2,"0")).join("")}
async function validSignature(raw:string,header:string,secret:string){if(!header.startsWith("sha256="))return false;const key=await crypto.subtle.importKey("raw",new TextEncoder().encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]);const sig=hex(await crypto.subtle.sign("HMAC",key,new TextEncoder().encode(raw)));const expected="sha256="+sig;if(expected.length!==header.length)return false;let diff=0;for(let i=0;i<expected.length;i++)diff|=expected.charCodeAt(i)^header.charCodeAt(i);return diff===0}
const rank:any={queued:0,sending:1,sent:2,delivered:3,read:4,failed:5,skipped:5};
async function refresh(admin:any,campaignId:string){const {data:rows}=await admin.from("whatsapp_campaign_recipients").select("status").eq("campaign_id",campaignId);const c={sent:0,delivered:0,read:0,failed:0,skipped:0,queued:0,sending:0} as any;for(const r of rows||[])c[r.status]=(c[r.status]||0)+1;const terminal=c.queued===0&&c.sending===0;const status=terminal?(c.failed>0?(c.sent+c.delivered+c.read>0?"partially_failed":"failed"):"completed"):"sending";await admin.from("whatsapp_campaigns").update({status,sent_count:c.sent+c.delivered+c.read,delivered_count:c.delivered+c.read,read_count:c.read,failed_count:c.failed,skipped_count:c.skipped,completed_at:terminal?new Date().toISOString():null,updated_at:new Date().toISOString()}).eq("id",campaignId)}
Deno.serve(async(req)=>{
 const verify=Deno.env.get("META_WHATSAPP_VERIFY_TOKEN")||"";if(req.method==="GET"){const u=new URL(req.url);const mode=u.searchParams.get("hub.mode"),token=u.searchParams.get("hub.verify_token"),challenge=u.searchParams.get("hub.challenge");if(mode==="subscribe"&&verify&&token===verify)return new Response(challenge||"",{status:200});return new Response("Forbidden",{status:403})}
 if(req.method!=="POST")return new Response("Method not allowed",{status:405});const secret=Deno.env.get("META_APP_SECRET")||"";if(!secret)return json({error:"Webhook app secret is not configured."},503);const raw=await req.text();if(!await validSignature(raw,req.headers.get("x-hub-signature-256")||"",secret))return json({error:"Invalid signature."},401);
 const admin=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);let payload:any;try{payload=JSON.parse(raw)}catch{return json({error:"Invalid JSON."},400)}const campaignIds=new Set<string>();
 for(const entry of payload?.entry||[])for(const change of entry?.changes||[]){const value=change?.value||{};for(const s of value?.statuses||[]){const id=String(s?.id||"");const next=String(s?.status||"");if(!id||!["sent","delivered","read","failed"].includes(next))continue;const {data:row}=await admin.from("whatsapp_campaign_recipients").select("id,campaign_id,status").eq("provider_message_id",id).maybeSingle();if(!row)continue;if(next!=="failed"&&rank[next]<rank[row.status])continue;const stamp=s?.timestamp?new Date(Number(s.timestamp)*1000).toISOString():new Date().toISOString();const patch:any={status:next,updated_at:new Date().toISOString()};if(next==="sent")patch.sent_at=stamp;if(next==="delivered")patch.delivered_at=stamp;if(next==="read")patch.read_at=stamp;if(next==="failed"){patch.failed_at=stamp;patch.error_code=String(s?.errors?.[0]?.code||"META_DELIVERY_FAILED");patch.error_message=String(s?.errors?.[0]?.title||s?.errors?.[0]?.message||"Meta reported delivery failure.").slice(0,1000)}await admin.from("whatsapp_campaign_recipients").update(patch).eq("id",row.id);campaignIds.add(String(row.campaign_id))}
 }
 for(const id of campaignIds)await refresh(admin,id);return json({received:true});
});