import { useEffect, useMemo, useState } from 'react'
import { AlertTriangle, BarChart3, CheckCircle2, ChevronDown, FileText, Link2, MessageCircle, RefreshCw, Search, Send, Settings2, ShieldCheck, Users, X } from 'lucide-react'
import { supabase } from '../lib/supabase'
import { friendlyErrorMessage } from '../lib/errors'
import TablePagination from './TablePagination'

type Application={id:string;name:string}
type Role='owner'|'admin'|'reviewer'
type Participant={id:string;participant_id:string;application_id:string;status:'active'|'completed'|'withdrawn';full_name:string|null;whatsapp_phone:string|null}
type Consent={participant_id:string;opted_in:boolean;phone_e164:string|null;source:string;opted_in_at:string|null;opted_out_at:string|null}
type Template={id:string;name:string;language:string;category:string|null;status:string;body_text:string|null;variable_count:number;supports_mvp:boolean;unsupported_reason:string|null;synced_at:string}
type Campaign={id:string;application_id:string;template_id:string;name:string;status:string;recipient_count:number;eligible_count:number;sent_count:number;delivered_count:number;read_count:number;failed_count:number;skipped_count:number;created_at:string}
type View='compose'|'templates'|'reports'|'connection'
type Mapping='name'|'participant_id'|'programme_name'|'phone'
const mappingOptions:[Mapping,string][]=[['name','Participant name'],['participant_id','Participant ID'],['programme_name','Programme name'],['phone','WhatsApp number']]

export default function WhatsAppWorkspace({organizationId,applications,role}:{organizationId:string;applications:Application[];role?:Role}){
  const canManage=role==='owner'||role==='admin'
  const [view,setView]=useState<View>('compose'),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false)
  const [error,setError]=useState(''),[notice,setNotice]=useState('')
  const [applicationId,setApplicationId]=useState(applications[0]?.id||''),[audience,setAudience]=useState<'all'|'active'|'completed'|'withdrawn'>('active'),[query,setQuery]=useState('')
  const [participants,setParticipants]=useState<Participant[]>([]),[consents,setConsents]=useState<Consent[]>([]),[templates,setTemplates]=useState<Template[]>([]),[campaigns,setCampaigns]=useState<Campaign[]>([])
  const [selected,setSelected]=useState<string[]>([]),[selectedTemplateId,setSelectedTemplateId]=useState(''),[mappings,setMappings]=useState<Mapping[]>([])
  const [page,setPage]=useState(1),[pageSize,setPageSize]=useState(50)
  const [connection,setConnection]=useState<{configured:boolean;validated:boolean;missing:string[];display_phone:string|null;verified_name:string|null;quality_rating:string|null;validation_error?:string|null}>({configured:false,validated:false,missing:[],display_phone:null,verified_name:null,quality_rating:null})

  useEffect(()=>{setApplicationId(c=>applications.some(a=>a.id===c)?c:(applications[0]?.id||''))},[applications])
  useEffect(()=>{if(!notice&&!error)return;const t=window.setTimeout(()=>{setNotice('');setError('')},6000);return()=>window.clearTimeout(t)},[notice,error])

  async function refreshConnection(validate=false){
    try{const {data,error}=await supabase.functions.invoke('whatsapp-status',{body:{organization_id:organizationId,validate}});if(error)throw error;if(data?.error)throw new Error(data.error);setConnection({configured:Boolean(data?.configured),validated:Boolean(data?.validated),missing:Array.isArray(data?.missing)?data.missing:[],display_phone:data?.display_phone||null,verified_name:data?.verified_name||null,quality_rating:data?.quality_rating||null,validation_error:data?.validation_error||null});if(validate&&data?.configured)setNotice('Meta WhatsApp connection validated.')}
    catch(e){setError(friendlyErrorMessage(e,'Could not check WhatsApp connection.'))}
  }
  async function refreshData(showLoading=false){
    if(showLoading)setLoading(true)
    try{
      const [p,c,t,ca]=await Promise.all([
        supabase.from('participants').select('id,participant_id,application_id,status,applicants(full_name,whatsapp_phone)').eq('organization_id',organizationId).order('participant_id'),
        supabase.from('whatsapp_consents').select('participant_id,opted_in,phone_e164,source,opted_in_at,opted_out_at').eq('organization_id',organizationId),
        supabase.from('whatsapp_templates').select('id,name,language,category,status,body_text,variable_count,supports_mvp,unsupported_reason,synced_at').eq('organization_id',organizationId).order('name'),
        supabase.from('whatsapp_campaigns').select('id,application_id,template_id,name,status,recipient_count,eligible_count,sent_count,delivered_count,read_count,failed_count,skipped_count,created_at').eq('organization_id',organizationId).order('created_at',{ascending:false}).limit(100),
      ])
      if(p.error)throw p.error;if(c.error)throw c.error;if(t.error)throw t.error;if(ca.error)throw ca.error
      setParticipants(((p.data||[]) as any[]).map(r=>({id:r.id,participant_id:r.participant_id,application_id:r.application_id,status:r.status,full_name:r.applicants?.full_name||null,whatsapp_phone:r.applicants?.whatsapp_phone||null})))
      setConsents((c.data||[]) as Consent[]);setTemplates((t.data||[]) as Template[]);setCampaigns((ca.data||[]) as Campaign[])
    }catch(e){setError(friendlyErrorMessage(e,'Could not load WhatsApp workspace.'))}finally{if(showLoading)setLoading(false)}
  }
  useEffect(()=>{void Promise.all([refreshConnection(false),refreshData(true)])},[organizationId])
  useEffect(()=>{if(!campaigns.some(c=>c.status==='queued'||c.status==='sending'))return;const t=window.setInterval(()=>void refreshData(false),5000);return()=>window.clearInterval(t)},[campaigns])

  const consentMap=useMemo(()=>new Map(consents.map(c=>[c.participant_id,c])),[consents])
  const programmeParticipants=useMemo(()=>participants.filter(p=>p.application_id===applicationId),[participants,applicationId])
  const visible=useMemo(()=>{const term=query.trim().toLowerCase();return programmeParticipants.filter(p=>(audience==='all'||p.status===audience)&&(!term||[p.full_name,p.participant_id,p.whatsapp_phone].filter(Boolean).join(' ').toLowerCase().includes(term)))},[programmeParticipants,audience,query])
  const pageCount=Math.max(1,Math.ceil(visible.length/pageSize)),paged=useMemo(()=>visible.slice((page-1)*pageSize,page*pageSize),[visible,page,pageSize])
  const selectedTemplate=templates.find(t=>t.id===selectedTemplateId)||null,approvedTemplates=templates.filter(t=>t.status==='approved')
  const programmeName=applications.find(a=>a.id===applicationId)?.name||'Programme'
  const validSelected=selected.filter(id=>{const p=programmeParticipants.find(x=>x.id===id),c=consentMap.get(id);return Boolean(p?.whatsapp_phone&&c?.opted_in&&c.phone_e164)})
  const preview=useMemo(()=>{let text=selectedTemplate?.body_text||'';mappings.forEach((m,i)=>{const label=mappingOptions.find(x=>x[0]===m)?.[1]||m;text=text.split('{{'+(i+1)+'}}').join('{{'+label+'}}')});return text},[selectedTemplate,mappings])
  useEffect(()=>{setPage(1)},[applicationId,audience,query]);useEffect(()=>{setPage(p=>Math.min(p,pageCount))},[pageCount])
  useEffect(()=>{const count=selectedTemplate?.variable_count||0,defaults:Mapping[]=['name','programme_name','participant_id','phone'];setMappings(Array.from({length:count},(_,i)=>defaults[i]||'name'))},[selectedTemplateId])

  async function syncTemplates(){setBusy(true);setError('');try{const {data,error}=await supabase.functions.invoke('sync-whatsapp-templates',{body:{organization_id:organizationId}});if(error)throw error;if(data?.error)throw new Error(data.error);setNotice(String(data?.synced||0)+' Meta template(s) synced.');await refreshData(false)}catch(e){setError(friendlyErrorMessage(e,'Could not sync WhatsApp templates.'))}finally{setBusy(false)}}
  async function setConsent(p:Participant,optedIn:boolean){if(!window.confirm(optedIn?'Confirm this participant explicitly agreed to receive WhatsApp messages. Record opt-in?':'Record this participant as opted out from WhatsApp messages?'))return;setBusy(true);setError('');try{const {data,error}=await supabase.functions.invoke('whatsapp-consent',{body:{organization_id:organizationId,participant_id:p.id,opted_in:optedIn,source:'admin_confirmed',proof_note:optedIn?'Consent confirmed by an ApplyFlow admin.':'Opt-out recorded by an ApplyFlow admin.'}});if(error)throw error;if(data?.error)throw new Error(data.error);setNotice(optedIn?'WhatsApp opt-in recorded.':'WhatsApp opt-out recorded.');await refreshData(false)}catch(e){setError(friendlyErrorMessage(e,'Could not update consent.'))}finally{setBusy(false)}}
  function toggle(id:string,checked:boolean){setSelected(c=>checked?[...new Set([...c,id])]:c.filter(x=>x!==id))}
  function togglePage(checked:boolean){const ids=paged.filter(p=>consentMap.get(p.id)?.opted_in&&consentMap.get(p.id)?.phone_e164).map(p=>p.id);setSelected(c=>checked?[...new Set([...c,...ids])]:c.filter(id=>!ids.includes(id)))}
  async function sendCampaign(){if(!connection.configured||!selectedTemplate||!validSelected.length||validSelected.length>200||!selectedTemplate.supports_mvp)return;setBusy(true);setError('');try{const {data,error}=await supabase.functions.invoke('send-whatsapp-campaign',{body:{organization_id:organizationId,application_id:applicationId,template_id:selectedTemplate.id,participant_ids:validSelected,variable_mappings:mappings,client_request_id:crypto.randomUUID(),name:selectedTemplate.name+' — '+programmeName}});if(error)throw error;if(data?.error)throw new Error(data.error);setNotice('Campaign queued: '+String(data?.eligible||0)+' eligible, '+String(data?.skipped||0)+' skipped.');setSelected([]);setView('reports');await refreshData(false)}catch(e){setError(friendlyErrorMessage(e,'Could not queue the WhatsApp campaign.'))}finally{setBusy(false)}}
  const totals=useMemo(()=>campaigns.reduce((a,c)=>({recipients:a.recipients+c.recipient_count,sent:a.sent+c.sent_count,delivered:a.delivered+c.delivered_count,read:a.read+c.read_count,failed:a.failed+c.failed_count}),{recipients:0,sent:0,delivered:0,read:0,failed:0}),[campaigns])

  if(loading)return <div className="loading-card card">Loading WhatsApp Center…</div>
  return <section className="email-workspace">
    <div className="page-heading compact email-page-heading"><div><p className="eyebrow">Communications</p><h1>WhatsApp Center</h1><p className="subtitle">Send approved templates to opted-in participants and track delivery through Meta.</p></div><div className={'email-provider-pill '+(connection.configured?'is-connected':'')}><span className="email-provider-dot"></span><div><strong>Meta WhatsApp</strong><small>{connection.configured?(connection.display_phone||'Configured'):'Not connected'}</small></div></div></div>
    {(error||notice)&&<div className={'email-inline-notice '+(error?'is-error':'is-success')}><div>{error?<X size={16}/>:<CheckCircle2 size={16}/>}</div><span>{error||notice}</span></div>}
    <div className="email-tabs"><button className={view==='compose'?'secondary-button':'text-button'} onClick={()=>setView('compose')}><MessageCircle size={16}/> Compose</button><button className={view==='templates'?'secondary-button':'text-button'} onClick={()=>setView('templates')}><FileText size={16}/> Templates</button><button className={view==='reports'?'secondary-button':'text-button'} onClick={()=>setView('reports')}><BarChart3 size={16}/> Reports</button><button className={view==='connection'?'secondary-button':'text-button'} onClick={()=>setView('connection')}><Settings2 size={16}/> Connection</button></div>
    {view==='compose'&&<div className="email-compose-layout"><div className="email-compose-main"><div className="card email-composer-card"><div className="card-header"><div><p className="eyebrow">Bulk WhatsApp</p><h2>Create campaign</h2><p>Only participants with a valid WhatsApp number and recorded opt-in are eligible.</p></div><MessageCircle size={20}/></div><div className="email-composer-form"><div className="email-composer-grid"><label>Programme<div className="participant-select-wrap"><select value={applicationId} onChange={e=>{setApplicationId(e.target.value);setSelected([])}}>{applications.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select><ChevronDown size={16}/></div></label><label>Audience<div className="participant-select-wrap"><select value={audience} onChange={e=>setAudience(e.target.value as typeof audience)}><option value="all">All participants</option><option value="active">Active / Enrolled</option><option value="completed">Completed</option><option value="withdrawn">Withdrawn</option></select><ChevronDown size={16}/></div></label><label>Approved Meta template<div className="participant-select-wrap"><select value={selectedTemplateId} onChange={e=>setSelectedTemplateId(e.target.value)}><option value="">Select template</option>{approvedTemplates.map(t=><option key={t.id} value={t.id}>{t.name} · {t.language}</option>)}</select><ChevronDown size={16}/></div></label></div>
    {selectedTemplate&&<div className="email-merge-fields"><div><strong>Template preview</strong><span>{selectedTemplate.category||'Meta template'} · {selectedTemplate.language}</span></div><p>{preview||'This template has no body text.'}</p>{!selectedTemplate.supports_mvp&&<p className="email-missing-config">{selectedTemplate.unsupported_reason}</p>}</div>}
    {selectedTemplate&&selectedTemplate.variable_count>0&&<div className="email-composer-grid">{Array.from({length:selectedTemplate.variable_count},(_,i)=><label key={i}>Variable {'{{'+(i+1)+'}}'}<div className="participant-select-wrap"><select value={mappings[i]||'name'} onChange={e=>setMappings(c=>c.map((m,j)=>j===i?e.target.value as Mapping:m))}>{mappingOptions.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><ChevronDown size={16}/></div></label>)}</div>}</div><div className="email-send-bar"><div><strong>{validSelected.length} eligible recipient{validSelected.length===1?'':'s'} selected</strong><span>{validSelected.length>200?'Reduce this campaign to 200 recipients or fewer.':connection.configured?'Campaign processing runs server-side after queueing.':'Connect Meta WhatsApp before sending.'}</span></div><button className="primary-button" onClick={sendCampaign} disabled={!canManage||busy||!connection.configured||!selectedTemplate||!selectedTemplate.supports_mvp||!validSelected.length||validSelected.length>200}><Send size={16}/>{busy?'Working…':'Queue campaign'}</button></div></div></div>
    <aside className="card email-recipient-card"><div className="card-header"><div><p className="eyebrow">Recipients</p><h2>Select participants</h2><p>{programmeName} · {visible.length} matching</p></div><Users size={20}/></div><div className="email-recipient-tools"><div className="search"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search participant…"/></div><label className="email-select-all"><input type="checkbox" checked={paged.length>0&&paged.filter(p=>consentMap.get(p.id)?.opted_in&&consentMap.get(p.id)?.phone_e164).every(p=>selected.includes(p.id))} onChange={e=>togglePage(e.target.checked)}/><span>Select eligible on this page</span></label></div><div className="email-recipient-list">{paged.length?paged.map(p=>{const c=consentMap.get(p.id),eligible=Boolean(c?.opted_in&&c.phone_e164);return <div key={p.id} className="email-recipient-row"><input type="checkbox" disabled={!eligible} checked={selected.includes(p.id)} onChange={e=>toggle(p.id,e.target.checked)}/><span><strong>{p.full_name||'Unnamed participant'}</strong><small>{p.whatsapp_phone||'No WhatsApp number'} · {p.participant_id}</small></span><div><i>{eligible?'Opted in':c?.opted_in===false?'Opted out':'Consent required'}</i>{canManage&&p.whatsapp_phone&&<button type="button" className="text-button" disabled={busy} onClick={()=>void setConsent(p,!c?.opted_in)}>{c?.opted_in?'Opt out':'Record opt-in'}</button>}</div></div>}):<div className="table-empty">No participants match this audience.</div>}</div><TablePagination total={visible.length} page={page} pageSize={pageSize} pageSizes={[50,100,150,200]} onPageChange={setPage} onPageSizeChange={s=>{setPageSize(s);setPage(1)}}/></aside></div>}
    {view==='templates'&&<div className="card table-card email-templates-card"><div className="card-header"><div><p className="eyebrow">Meta templates</p><h2>Approved message templates</h2><p>Sync templates from the connected WhatsApp Business Account.</p></div><button className="secondary-button" disabled={busy||!connection.configured} onClick={syncTemplates}><RefreshCw size={16}/>{busy?'Syncing…':'Sync templates'}</button></div><div className="table-wrap"><table><thead><tr><th>Template</th><th>Language</th><th>Category</th><th>Variables</th><th>Status</th><th>Synced</th></tr></thead><tbody>{templates.length?templates.map(t=><tr key={t.id}><td><strong>{t.name}</strong>{t.unsupported_reason&&<span className="table-sub">{t.unsupported_reason}</span>}</td><td>{t.language}</td><td>{t.category||'—'}</td><td>{t.variable_count}</td><td><span className={'status '+(t.status==='approved'?'green':t.status==='rejected'?'amber':'neutral')}>{t.status}</span></td><td>{new Date(t.synced_at).toLocaleString()}</td></tr>):<tr><td colSpan={6}><div className="table-empty">{connection.configured?'No templates synced yet.':'Connect Meta WhatsApp first.'}</div></td></tr>}</tbody></table></div></div>}
    {view==='reports'&&<div className="email-report-workspace"><div className="stats-grid email-report-stats"><div className="card stat-card"><div className="stat-icon"><Users size={16}/></div><div><p className="eyebrow">Recipients</p><div className="stat-value">{totals.recipients}</div></div></div><div className="card stat-card"><div className="stat-icon"><Send size={16}/></div><div><p className="eyebrow">Sent</p><div className="stat-value">{totals.sent}</div></div></div><div className="card stat-card"><div className="stat-icon"><CheckCircle2 size={16}/></div><div><p className="eyebrow">Delivered</p><div className="stat-value">{totals.delivered}</div><p className="muted">{totals.read} read</p></div></div><div className="card stat-card"><div className="stat-icon"><AlertTriangle size={16}/></div><div><p className="eyebrow">Failed</p><div className="stat-value">{totals.failed}</div></div></div></div><div className="card table-card email-report-card"><div className="card-header"><div><p className="eyebrow">Campaign history</p><h2>WhatsApp delivery reports</h2><p>Webhook events update sent, delivered, read and failed counts.</p></div><button className="secondary-button" onClick={()=>void refreshData(false)}><RefreshCw size={16}/> Refresh</button></div><div className="table-wrap"><table><thead><tr><th>Campaign</th><th>Recipients</th><th>Sent</th><th>Delivered</th><th>Read</th><th>Failed</th><th>Status</th><th>Date</th></tr></thead><tbody>{campaigns.length?campaigns.map(c=><tr key={c.id}><td><strong>{c.name}</strong><span className="table-sub">{applications.find(a=>a.id===c.application_id)?.name||'Programme'}</span></td><td>{c.recipient_count}<span className="table-sub">{c.skipped_count} skipped</span></td><td>{c.sent_count}</td><td>{c.delivered_count}</td><td>{c.read_count}</td><td>{c.failed_count}</td><td><span className={'status '+(c.status==='completed'?'green':c.status==='failed'||c.status==='partially_failed'?'amber':'blue')}>{c.status.replaceAll('_',' ')}</span></td><td>{new Date(c.created_at).toLocaleString()}</td></tr>):<tr><td colSpan={8}><div className="table-empty">No WhatsApp campaigns yet.</div></td></tr>}</tbody></table></div></div></div>}
    {view==='connection'&&<div className="email-connection-layout"><div className="card email-connection-card"><div className="email-connection-logo"><MessageCircle size={24}/></div><div className="email-connection-copy"><p className="eyebrow">Messaging provider</p><h2>Meta WhatsApp Cloud API</h2><p>Credentials stay in Supabase Edge Function Secrets and are never exposed to the browser.</p><div className={'email-connection-status '+(connection.configured?'is-connected':'')}><span></span><strong>{connection.configured?(connection.validated?'Connected & validated':'Configured'):'Not configured'}</strong>{connection.display_phone&&<small>{connection.display_phone}{connection.verified_name?' · '+connection.verified_name:''}</small>}</div>{connection.missing.length>0&&<p className="email-missing-config">Missing server secrets: {connection.missing.join(', ')}</p>}{connection.validation_error&&<p className="email-missing-config">{connection.validation_error}</p>}</div><button className="primary-button" disabled={busy||!canManage} onClick={()=>void refreshConnection(true)}><Link2 size={16}/> Validate Meta</button></div><div className="card email-security-card"><div className="card-header"><div><p className="eyebrow">Secure setup</p><h2>Required Meta configuration</h2></div><ShieldCheck size={20}/></div><div className="email-setup-list"><div><span>1</span><div><strong>Sending credentials</strong><p>META_WHATSAPP_ACCESS_TOKEN, META_WHATSAPP_PHONE_NUMBER_ID, META_WHATSAPP_BUSINESS_ACCOUNT_ID and META_GRAPH_API_VERSION.</p></div></div><div><span>2</span><div><strong>Webhook security</strong><p>META_WHATSAPP_VERIFY_TOKEN and META_APP_SECRET protect delivery callbacks.</p></div></div><div><span>3</span><div><strong>Consent</strong><p>Only participants with a recorded opt-in and normalized WhatsApp number can be selected.</p></div></div></div></div></div>}
  </section>
}
